//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhovRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ahov_Connection : DbContext
    {
        public Ahov_Connection()
            : base("name=Ahov_Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barrel> barrel { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<citybuilding> citybuilding { get; set; }
        public virtual DbSet<matter> matter { get; set; }
        public virtual DbSet<organization> organization { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<usertoorg> usertoorg { get; set; }
    }
}
