//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhovRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class barrel
    {
        public int BarrelId { get; set; }
        public string Name { get; set; }
        public string Draining { get; set; }
        public string SaveType { get; set; }
        public double Q { get; set; }
        public double H { get; set; }
        public int MatterId { get; set; }
        public int OrgId { get; set; }
    
        public virtual matter matter { get; set; }
    }
}
