//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhovRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class citybuilding
    {
        public int BuildingId { get; set; }
        public string TypeName { get; set; }
        public double Kp { get; set; }
        public double Ay { get; set; }
        public int City_CityId { get; set; }
    
        public virtual city city { get; set; }
    }
}
