//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhovRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class matter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matter()
        {
            this.barrel = new HashSet<barrel>();
        }
    
        public int MatterId { get; set; }
        public string Name { get; set; }
        public double Cv { get; set; }
        public double Tcg { get; set; }
        public double Tck { get; set; }
        public double I { get; set; }
        public double Pg { get; set; }
        public double M { get; set; }
        public double E { get; set; }
        public double Asm { get; set; }
        public double Bsm { get; set; }
        public double Ap { get; set; }
        public double Bp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<barrel> barrel { get; set; }
    }
}
