//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhovRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        public int OrgId { get; set; }
        public string OgranizationName { get; set; }
        public int PersonalCount { get; set; }
        public double Kf { get; set; }
        public double Ro { get; set; }
        public double Rz { get; set; }
        public double Top { get; set; }
        public double Tow { get; set; }
        public double Gdl { get; set; }
        public double Gl { get; set; }
        public double W { get; set; }
        public double Aao { get; set; }
        public int City_CityId { get; set; }
        public double Bw { get; set; }
        public double Bw_ch { get; set; }
        public double Bu { get; set; }
        public double Bu_ch { get; set; }
        public double Ba { get; set; }
        public double Ba_ch { get; set; }
    
        public virtual city city { get; set; }
    }
}
